#ifndef __SYSTEM_TABLE_H__
#define __SYSTEM_TABLE_H__

#include "EFI/DataTypes.h"
#include "EFI/Services.h"
#include "EFI/Protocols/SimpleTextProtocol.h"
#include "EFI/ConfigurationTables.h"

// SystemTable.h: UEFI system table definition

#define GET_EFI_SYSTEM_TABLE_REVISION(major, minor) ((major<<16 | minor))

#define EFI_SYSTEM_TABLE_SIGNATURE 0x5453595320494249
#define EFI_2_100_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 100)
#define EFI_2_90_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 90)
#define EFI_2_80_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 80)
#define EFI_2_70_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 70)
#define EFI_2_60_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 60)
#define EFI_2_50_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 50)
#define EFI_2_40_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 40)
#define EFI_2_31_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 31)
#define EFI_2_30_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 30)
#define EFI_2_20_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 20)
#define EFI_2_10_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 10)
#define EFI_2_00_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(2, 00)
#define EFI_1_10_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(1, 10)
#define EFI_1_02_SYSTEM_TABLE_REVISION		GET_EFI_SYSTEM_TABLE_REVISION(1, 02)
#define EFI_SPECIFICATION_VERSION			EFI_SYSTEM_TABLE_REVISION
#define EFI_SYSTEM_TABLE_REVISION			EFI_2_100_SYSTEM_TABLE_REVISION

typedef struct s_EFI_SYSTEM_TABLE {
	EFI_TABLE_HEADER Hdr;
	CHAR16* FirmwareVendor;
	UINT32 FirmwareRevision;
	EFI_HANDLE ConsoleInHandle;
	EFI_SIMPLE_TEXT_INPUT_PROTOCOL* ConIn; // Console input
	EFI_HANDLE ConsoleOutHandle;
	EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL* ConOut; // Console output
	EFI_HANDLE StandardErrorHandle;
	EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL* StdErr;
	EFI_RUNTIME_SERVICES* RuntimeServices;
	EFI_BOOT_SERVICES* BootServices;
	UINTN NumberOfTableEntries;
	EFI_CONFIGURATION_TABLE* ConfigurationTable;
} EFI_SYSTEM_TABLE;

#endif
